//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Databas_med_kod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boklån
    {
        public string PersonNr { get; set; }
        public int BokNr { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Bok Böcker { get; set; }
        public virtual Person Table { get; set; }
    }
}
